### ISSUE TITLE
Error on prefetch for foreman_config_entry

### ISSUE THREAD

**Issue by treydock** [theforeman/puppet-foreman#309]
When I run Puppet on my Foreman host after updating to theforeman/foreman 3.0.0 I get the following error (full backtrace).

This is with puppet-3.6.2 on CentOS 6.5.

```
Error: Could not prefetch foreman_config_entry provider 'cli': undefined method `intern' for nil:NilClass
/usr/lib/ruby/site_ruby/1.8/puppet/type.rb:1691:in `provider'
/usr/lib/ruby/site_ruby/1.8/puppet/type.rb:1904:in `provider='
/var/lib/puppet/lib/puppet/provider/foreman_config_entry/cli.rb:58:in `prefetch'
/var/lib/puppet/lib/puppet/provider/foreman_config_entry/cli.rb:52:in `each'
/var/lib/puppet/lib/puppet/provider/foreman_config_entry/cli.rb:52:in `prefetch'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:277:in `prefetch'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:167:in `prefetch_if_necessary'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:67:in `evaluate'
/usr/lib/ruby/site_ruby/1.8/puppet/graph/relationship_graph.rb:116:in `call'
/usr/lib/ruby/site_ruby/1.8/puppet/graph/relationship_graph.rb:116:in `traverse'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:108:in `evaluate'
/usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:167:in `apply'
/usr/lib/ruby/site_ruby/1.8/puppet/util/log.rb:149:in `with_destination'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction/report.rb:112:in `as_logging_destination'
/usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:166:in `apply'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:117:in `apply_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:161:in `benchmark'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:160:in `benchmark'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:116:in `apply_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:191:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:47:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent/locker.rb:20:in `lock'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:47:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:117:in `with_client'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:44:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:82:in `run_in_fork'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:43:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:179:in `call'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:179:in `controlled_run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:41:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application/agent.rb:355:in `onetime'
/usr/lib/ruby/site_ruby/1.8/puppet/application/agent.rb:321:in `run_command'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:371:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:477:in `plugin_hook'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:371:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:479:in `exit_on_fail'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:371:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:137:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:91:in `execute'
/usr/bin/puppet:8
```

The location of #intern call on nil:

https://github.com/puppetlabs/puppet/blob/3.6.2/lib/puppet/type.rb#L1691

**Comment by domcleal** [comment]
Could you pastebin the output of /usr/share/foreman/script/foreman-config?  We check for a nil value in the instances method, but I guess we're generating a nil name perhaps..

**Comment by treydock** [comment]
The issue, I think, is the config keys didn't exist as I was on Foreman 1.6.0 when I got those errors.  I've since upgrades to 1.7.3 to resolve that issue and a few others that were resolved by upgrading.  I looked and noticed the Foreman setup rake task that set values when things like db:seed were run, did not seem to exist in 1.6.0.

**Comment by domcleal** [comment]
Ah right, I did wonder when I saw your -users post whether this was on 1.6.0.  3.0.x supports only 1.7 and 1.8 for that reason, we're trying to just support two stable (or one stable + shortly-to-be stable) versions at any one time in a release.  2.3.x is the release for 1.7 and 1.6 support, or 2.2.x for 1.6 and 1.5.
