### ISSUE TITLE
Foreman::Rake[db:migrate] fails when using puppet 4

### ISSUE THREAD

**Issue by madAndroid** [theforeman/puppet-foreman#385]
Hi,

I'm seeing the `Foreman::Rake` execs failing when using the puppetlabs AIO packages:
```
==> core: Info: Foreman::Rake[db:migrate]: Scheduling refresh of Exec[foreman-rake-db:migrate]
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: rake aborted!
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: LoadError: cannot load such file -- facter
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: /usr/share/foreman/lib/tasks/reset_permissions.rake:1:in `<top (required)>'
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `block in load'
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/engine.rb:425:in `block in load_tasks'
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/engine.rb:425:in `each'
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/engine.rb:425:in `load_tasks'
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/application.rb:145:in `load_tasks'
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: /usr/share/foreman/Rakefile:7:in `<top (required)>'
==> core: Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: (See full trace by running task with --trace)
==> core: Error: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]: Failed to call refresh: /usr/sbin/foreman-rake db:migrate returned 1 instead of one of [0]
==> core: Error: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]: /usr/sbin/foreman-rake db:migrate returned 1 instead of one of [0]
==> core: Notice: /Stage[main]/Foreman::Database/Foreman_config_entry[db_pending_seed]/value: value changed '' to 'false'
```

This is on ubuntu 14.04, puppet version:
```
vagrant@core:~$ /opt/puppetlabs/bin/puppet --version
4.3.1
```

My profile module contains:

```puppet
class { '::puppet':
    server                  => true,
    server_implementation   => 'puppetserver',
    server_foreman          => false,
    server_git_repo         => true,
    client_package          => 'puppet-agent',
    logdir                  => '/var/log/puppetlabs/puppet',
    rundir                  => '/var/run/puppetlabs',
    ssldir                  => '/etc/puppetlabs/puppet/ssl',
    server_ssl_dir          => '/etc/puppetlabs/puppet/ssl',
    vardir                  => '/opt/puppetlabs/puppet/cache',
}

class { '::foreman':
    admin_password          => 'testpass'
}
class { '::foreman_proxy': }
```

**Comment by mmoll** [comment]
Foreman is not supported with Puppet 4, yet, and even less with AIO packages. AIO packaging is bringing its own Ruby, making it impossible to load e.g. facter into the system Ruby we use, leading to the error seen.

**Comment by ekohl** [comment]
Adding to that: we would like to have it supported though. I'd also expect that the puppet module would need fewer arguments and autodetect the AIO install.

**Comment by mmoll** [comment]
kind of related: #367 - I still think leveraging the whole AIO/non-AIO/OS detection logic of theforeman-puppet should be used by having -foreman depend on -puppet would be the best way. :boom:

**Comment by madAndroid** [comment]
Okay, thanks for the explanation - I had seen some movement in a few commits around puppet 4, but didn't realise there was still a way to go.

**Comment by mmoll** [comment]
Yes, changes were made to get this Puppet module itself Puppet 4 compatible as-is, but there are still more changes to make until Foreman with all its subsystems will be compatible with Puppet 4 _and_ AIO packages. BTW, all help would be welcome. :)

**Comment by domcleal** [comment]
While I entirely agree that there are loads of systems that aren't compatible, the issue here looks like one we could address in the Debian packaging by switching to a vendored version of Facter.

The 'foreman' package has a dep on the 'facter' package and expects to load it from the regular shared Ruby paths under /usr etc.  We could include bundler.d/facter.rb in the core package build so it's cached as a gem using Bundler instead of using the system package.

(Facter's only used as a dep in Foreman core for FQDN resolution etc.)

**Comment by mmoll** [comment]
@domcleal true... I'll take the DEB part. :)

**Comment by pchineye** [comment]
Team:

I am seeing similar ERROR on foreman 1.12 install on  rhel 6 puppet 4:

/Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]: Failed to call refresh: /usr/sbin/foreman-rake db:migrate returned 1 instead of one of [0]
 /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]: /usr/sbin/foreman-rake db:migrate returned 1 instead of one of [0]
 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]: Failed to call refresh: /usr/sbin/foreman-rake db:seed returned 1 instead of one of [0]
 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]: /usr/sbin/foreman-rake db:seed returned 1 instead of one of [0]
 /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[nydlx0380.us.net.intra]: Could not evaluate: Proxy lx00.example.com cannot be retrieved: unknown error (response 500)
-----------------------------------
[lx00 ~]$ puppet status
{
  "is_alive": true,
  "version": "4.5.3"
}
[lx00 ~]$ puppet --version
4.5.3
--------------------------------------
please assist

**Comment by mmoll** [comment]
please open a new issue for his.

**Comment by pchineye** [comment]
looks like I already did as....pchineye
