### ISSUE TITLE
Evaluation Error: Error while evaluating a Method call

### ISSUE THREAD

**Issue by flybyray** [theforeman/puppet-foreman#887]
```
[ERROR 2020-10-08T12:02:54 main]  Evaluation Error: Error while evaluating a Method call, 'regsubst' parameter 'target' expects a value of type Array or String, got Undef (file: /usr/share/foreman-installer/modules/foreman/manifests/plugin/tasks.pp, line: 14, column: 48) on node
```

https://github.com/theforeman/puppet-foreman/blob/026d47434316b8ae318c5e42936edc12859ab475/manifests/plugin/tasks.pp#L14

**Comment by ekohl** [comment]
Did you by any chance `include foreman::plugin::tasks` before the `include foreman`? Perhaps to be safe, the file should `include foreman` explicitly so the variable is guaranteed to be defined.

**Comment by flybyray** [comment]
by chance it is a release from rpm.
```
# dnf list foreman-installer |& grep foreman-installer
foreman-installer.noarch 1:2.1.3-1.el8 @foreman
```

```
# rpm -ql foreman-installer |& grep /usr/share/foreman-installer/modules/foreman/manifests/plugin/tasks.pp
/usr/share/foreman-installer/modules/foreman/manifests/plugin/tasks.pp
```

If i change the file on disk and run a foreman-installer command again.
```
# foreman-installer   --no-enable-foreman   --no-enable-foreman-cli   --no-enable-puppet   --no-enable-foreman-proxy   --enable-foreman-plugin-ansible   --enable-foreman-proxy-plugin-ansible

Traceback (most recent call last):
        11: from /usr/sbin/foreman-installer:8:in `<main>'
        10: from /usr/share/gems/gems/kafo-4.1.0/lib/kafo/kafo_configure.rb:162:in `run'
         9: from /usr/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
         8: from /usr/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `new'
         7: from /usr/share/gems/gems/kafo-4.1.0/lib/kafo/kafo_configure.rb:99:in `initialize'
         6: from /usr/share/gems/gems/kafo-4.1.0/lib/kafo/kafo_configure.rb:284:in `set_parameters'
         5: from /usr/share/gems/gems/kafo-4.1.0/lib/kafo/configuration.rb:245:in `preset_defaults_from_puppet'
         4: from /usr/share/gems/gems/kafo-4.1.0/lib/kafo/configuration.rb:235:in `params'
         3: from /usr/share/gems/gems/kafo-4.1.0/lib/kafo/configuration.rb:110:in `modules'
         2: from /usr/share/gems/gems/kafo-4.1.0/lib/kafo/configuration.rb:110:in `map'
         1: from /usr/share/gems/gems/kafo-4.1.0/lib/kafo/configuration.rb:110:in `block in modules'
/usr/share/gems/gems/kafo-4.1.0/lib/kafo/puppet_module.rb:69:in `parse': No Puppet module parser is installed and no cache of the file /usr/share/foreman-installer/modules/foreman/manifests/plugin/tasks.pp is available. Please check debug logs and install optional dependencies for the parser. (Kafo::ParserError)
```

**Comment by ekohl** [comment]
`--no-enable-foreman` and `--enable-foreman-plugin-*` is conflicting. You can't disable Foreman but Foreman enable plugins.
